language: node_js
node_js:
    - 10
cache: yarn
before_install:
    - git checkout v0.0.8
install:
    - yarn
script:
    - yarn docs:build
    
after_success:
    - cd docs/.vuepress/dist
    - git init
    - git config --global user.name "hellottxo"
    - git config --global user.email "654720416@qq.com"
    - git add -A
    - git commit -m 'deploy'
    - git push --force "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
env:
  global:
    - GH_REF: github.com/Hellottxo/xo-ui.git